name: ✨ Feature Request
description: 새로운 기능 요청을 위한 이슈
title: "[FEATURE] "
labels: ["enhancement"]
projects: ["day-by-spring"]
body:
  - type: markdown
    attributes:
      value: |
        # ✨ Feature Request Template
        
        새로운 기능 요청을 제안하고 논의하기 위한 템플릿입니다.
        기능의 목적과 가치를 명확히 설명해 주세요.

  - type: input
    id: feature-title
    attributes:
      label: "📋 기능 제목"
      description: "요청하는 기능의 제목을 입력하세요"
      placeholder: "예: 도서 추천 시스템 구현"
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: "🔧 기능 유형"
      description: "요청하는 기능의 유형을 선택하세요"
      options:
        - new-feature
        - enhancement
        - performance
        - ui-improvement
        - integration
        - automation
        - monitoring
    validations:
      required: true

  - type: dropdown
    id: domain
    attributes:
      label: "🏢 도메인"
      description: "기능이 속할 도메인을 선택하세요"
      options:
        - member
        - book
        - order
        - loan
        - payment
        - statistics
        - system
        - infrastructure
        - ui
        - api
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "🔥 우선순위"
      description: "기능의 우선순위를 선택하세요"
      options:
        - critical
        - high
        - medium
        - low
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: "❓ 해결하고자 하는 문제"
      description: "이 기능이 해결하고자 하는 문제나 니즈를 설명하세요"
      placeholder: |
        ## 현재 상황
        - 현재 시스템에서 어떤 문제나 불편함이 있는지 설명하세요
        
        ## 사용자 관점
        - 사용자들이 어떤 어려움을 겪고 있는지 설명하세요
        
        ## 비즈니스 관점
        - 비즈니스에 어떤 영향을 미치는지 설명하세요
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: "💡 제안하는 해결책"
      description: "문제를 해결하기 위해 제안하는 기능에 대해 설명하세요"
      placeholder: |
        ## 기능 개요
        - 어떤 기능을 구현할지 간략히 설명하세요
        
        ## 주요 특징
        - 이 기능의 핵심적인 특징들을 나열하세요
        
        ## 사용자 워크플로우
        - 사용자가 이 기능을 어떻게 사용하게 될지 설명하세요
    validations:
      required: true

  - type: textarea
    id: user-stories
    attributes:
      label: "👤 사용자 스토리"
      description: "사용자 관점에서 이 기능의 가치를 설명하세요"
      placeholder: |
        **As a** 도서관 이용자
        **I want** 내 독서 이력을 기반으로 추천 도서를 받고 싶다
        **So that** 관심사에 맞는 새로운 책을 쉽게 발견할 수 있다
        
        **As a** 도서관 관리자
        **I want** 인기 도서와 추천 통계를 확인하고 싶다
        **So that** 도서 구매 결정에 데이터를 활용할 수 있다
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "✅ 인수 기준"
      description: "이 기능이 완료되었다고 판단할 수 있는 조건들을 나열하세요"
      placeholder: |
        - [ ] 사용자의 대여 이력을 분석하여 추천 로직을 구현한다
        - [ ] 장르, 저자, 키워드 기반의 추천 알고리즘을 제공한다
        - [ ] 추천 결과를 사용자에게 표시하는 UI를 구현한다
        - [ ] 추천 정확도를 측정하고 개선할 수 있는 피드백 시스템을 구축한다
        - [ ] 관리자용 추천 통계 대시보드를 제공한다
        - [ ] 추천 시스템의 성능이 요구사항을 만족한다 (응답시간 < 2초)
    validations:
      required: true

  - type: textarea
    id: technical-requirements
    attributes:
      label: "🔧 기술적 요구사항"
      description: "구현에 필요한 기술적 사항들을 설명하세요"
      placeholder: |
        ## 아키텍처
        - 마이크로서비스 아키텍처 고려
        - 추천 엔진을 별도 서비스로 분리
        
        ## 성능 요구사항
        - 추천 생성 시간: 2초 이내
        - 동시 사용자: 1000명 지원
        
        ## 데이터 요구사항
        - 사용자 행동 데이터 수집
        - 추천 이력 저장 및 분석
        
        ## 외부 연동
        - 외부 도서 정보 API 연동 (선택사항)
        - 머신러닝 모델 서빙 환경
    validations:
      required: true

  - type: textarea
    id: mockups-wireframes
    attributes:
      label: "🎨 UI/UX 설계"
      description: "UI가 포함된 기능인 경우 화면 설계나 와이어프레임을 설명하세요"
      placeholder: |
        ## 화면 구성
        - 추천 도서 목록 페이지
        - 개인화된 대시보드
        - 추천 설정 페이지
        
        ## 사용자 경험
        - 직관적인 추천 이유 설명
        - 추천 도서에 대한 액션 (관심, 비관심, 대여)
        - 추천 정확도 피드백
        
        ## 반응형 설계
        - 모바일/태블릿 최적화
        - 접근성 고려 (WCAG 2.1)

  - type: textarea
    id: alternatives
    attributes:
      label: "🔄 대안 고려사항"
      description: "이 기능 외에 고려했던 다른 해결책이 있다면 설명하세요"
      placeholder: |
        ## 고려했던 대안들
        1. **외부 추천 서비스 연동**: 비용 문제로 제외
        2. **단순 인기도 기반 추천**: 개인화 부족으로 제외
        3. **수동 큐레이션**: 확장성 문제로 제외
        
        ## 선택한 이유
        - 자체 데이터 활용으로 개인화 가능
        - 점진적 개선 가능한 구조
        - 비용 효율적

  - type: textarea
    id: implementation-plan
    attributes:
      label: "📋 구현 계획"
      description: "이 기능을 어떻게 단계적으로 구현할지 계획을 제시하세요"
      placeholder: |
        ## Phase 1: 기본 추천 시스템 (4주)
        - 사용자 행동 데이터 수집 구조 구축
        - 간단한 협업 필터링 알고리즘 구현
        - 기본 추천 API 개발
        
        ## Phase 2: UI 및 사용자 경험 (3주)  
        - 추천 결과 표시 화면 개발
        - 사용자 피드백 수집 기능
        - 추천 설정 관리 기능
        
        ## Phase 3: 고도화 및 최적화 (3주)
        - 머신러닝 모델 적용
        - 성능 최적화
        - A/B 테스트 환경 구축

  - type: input
    id: estimated-effort
    attributes:
      label: "⏱️ 예상 개발 기간"
      description: "전체 기능 완료까지 예상되는 기간"
      placeholder: "예: 10주 (3개월)"

  - type: textarea
    id: impact-assessment
    attributes:
      label: "📊 영향도 평가"
      description: "이 기능이 시스템과 사용자에게 미칠 영향을 평가하세요"
      placeholder: |
        ## 긍정적 영향
        - 사용자 만족도 향상
        - 도서 대여율 증가 예상
        - 데이터 기반 의사결정 가능
        
        ## 잠재적 위험
        - 시스템 복잡도 증가
        - 성능 부하 가능성
        - 개인정보 처리 이슈
        
        ## 완화 방안
        - 단계적 출시로 안정성 확보
        - 성능 모니터링 강화
        - 개인정보보호 정책 수립

  - type: checkboxes
    id: checklist
    attributes:
      label: "✅ 체크리스트"
      description: "기능 요청 전 확인사항"
      options:
        - label: "유사한 기능 요청이 이미 있는지 확인했습니다"
          required: true
        - label: "비즈니스 가치와 사용자 니즈를 명확히 설명했습니다"
          required: true
        - label: "기술적 실현 가능성을 고려했습니다"
          required: true
        - label: "구현 우선순위와 일정을 현실적으로 제안했습니다"
          required: true

  - type: input
    id: milestone
    attributes:
      label: "🎯 마일스톤"
      description: "이 기능이 포함될 마일스톤"
      placeholder: "예: Phase 2: Advanced Features"